<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE8iphdw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE8iphdw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE8iphdw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE8iphdw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE8iphdw\appProdProjectContainer([
    'container.build_hash' => 'E8iphdw',
    'container.build_id' => 'd3923798',
    'container.build_time' => 1559758486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE8iphdw');
