<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG7s7hob\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG7s7hob/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG7s7hob.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG7s7hob\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerG7s7hob\appDevDebugProjectContainer([
    'container.build_hash' => 'G7s7hob',
    'container.build_id' => '34735422',
    'container.build_time' => 1560170905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG7s7hob');
