<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxbfuhl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxbfuhl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZxbfuhl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZxbfuhl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZxbfuhl\appDevDebugProjectContainer([
    'container.build_hash' => 'Zxbfuhl',
    'container.build_id' => '8e494cb9',
    'container.build_time' => 1559927813,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxbfuhl');
