<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkay7h8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkay7h8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXkay7h8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXkay7h8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXkay7h8\appDevDebugProjectContainer([
    'container.build_hash' => 'Xkay7h8',
    'container.build_id' => 'a3f77b99',
    'container.build_time' => 1559893354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkay7h8');
